import Head from "next/head";
import Image from "next/image";
// import styles from "./layout.module.css";
// import utilStyles from "../styles/utils.module.css";
import Link from "next/link";
import Footer from "./Footer";
import Navigation from "./Navigation";

export const siteTitle = "Ali Tursucular GitHub blog website";

const Layout: React.FC<{ children: React.ReactNode; home?: boolean }> = ({ children, home }) => {
    return (
        <>
            <Head>
                <title>{siteTitle}</title>
                <link rel="icon" href="/pinecone-software-limited-favicon.ico" />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="og:title" content={siteTitle} />
            </Head>
            <header>
                <Navigation home={home} />
            </header>
            {/* <header>
                <Link href="/">
                    alitursucular.github.io
                    <Image
                        priority
                        src="/images/pinecone-software-limited-small-logo.png"
                        height={44}
                        width={44}
                        alt="Pinecone Software Limited company small logo"
                    />
                </Link>
                <Link href="/about">About</Link>
                <Link href="/cv">CV</Link>
            </header> */}
            <main>{children}</main>
            {!home && (
                <div>
                    <Link href="/">← Back to home</Link>
                </div>
            )}
            <Footer />
        </>
    );
};

export default Layout;
