import Head from "next/head";
import Image from "next/image";
// import styles from "./layout.module.scss";
// import utilStyles from "../styles/utils.module.scss";
import Link from "next/link";
import Footer from "./Footer";
import Navigation from "./Navigation";

export const siteTitle = "Ali Tursucular GitHub blog website";

const Layout: React.FC<{ children: React.ReactNode; home: boolean }> = ({ children, home }) => {
    return (
        <>
            <Head>
                <title>{siteTitle}</title>
                <link rel="icon" href="/pinecone-software-limited-favicon.ico" />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="og:title" content={siteTitle} />
            </Head>
            <header>
                <Navigation home={home} />
            </header>
            <main>{children}</main>
            {!home && (
                <div>
                    <Link href="/">← Back to home</Link>
                </div>
            )}
            <Footer />
        </>
    );
};

export default Layout;
